//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIBankingASP.NET.com.quantiguous.inw {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.quantiguous.com/services", ConfigurationName="com.quantiguous.inw.InwardRemittanceByPartnerService")]
    public interface InwardRemittanceByPartnerService {
        
        // CODEGEN: Generating message contract since the operation remit is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/remit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIBankingASP.NET.com.quantiguous.inw.remitResponse1 remit(APIBankingASP.NET.com.quantiguous.inw.remitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/remit", ReplyAction="*")]
        System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.inw.remitResponse1> remitAsync(APIBankingASP.NET.com.quantiguous.inw.remitRequest request);
        
        // CODEGEN: Generating message contract since the operation getBalance is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/getBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIBankingASP.NET.com.quantiguous.inw.getBalanceResponse1 getBalance(APIBankingASP.NET.com.quantiguous.inw.getBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/getBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.inw.getBalanceResponse1> getBalanceAsync(APIBankingASP.NET.com.quantiguous.inw.getBalanceRequest request);
        
        // CODEGEN: Generating message contract since the operation getRemittanceStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/getRemittanceStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIBankingASP.NET.com.quantiguous.inw.getRemittanceStatusResponse1 getRemittanceStatus(APIBankingASP.NET.com.quantiguous.inw.getRemittanceStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/getRemittanceStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.inw.getRemittanceStatusResponse1> getRemittanceStatusAsync(APIBankingASP.NET.com.quantiguous.inw.getRemittanceStatusRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class remit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string uniqueRequestNoField;
        
        private string partnerCodeField;
        
        private remitterType remitterTypeField;
        
        private nameType remitterNameField;
        
        private AddressType remitterAddressField;
        
        private contactType remitterContactField;
        
        private IdentityType[] remitterIdentitiesField;
        
        private beneficiaryType beneficiaryTypeField;
        
        private nameType beneficiaryNameField;
        
        private AddressType beneficiaryAddressField;
        
        private contactType beneficiaryContactField;
        
        private IdentityType[] beneficiaryIdentitiesField;
        
        private string beneficiaryAccountNoField;
        
        private string beneficiaryIFSCField;
        
        private System.Nullable<transferTypeType> transferTypeField;
        
        private System.Nullable<currencyCodeType> transferCurrencyCodeField;
        
        private float transferAmountField;
        
        private string remitterToBeneficiaryInfoField;
        
        private string purposeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string uniqueRequestNo {
            get {
                return this.uniqueRequestNoField;
            }
            set {
                this.uniqueRequestNoField = value;
                this.RaisePropertyChanged("uniqueRequestNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", IsNullable=true, Order=2)]
        public string partnerCode {
            get {
                return this.partnerCodeField;
            }
            set {
                this.partnerCodeField = value;
                this.RaisePropertyChanged("partnerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public remitterType remitterType {
            get {
                return this.remitterTypeField;
            }
            set {
                this.remitterTypeField = value;
                this.RaisePropertyChanged("remitterType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public nameType remitterName {
            get {
                return this.remitterNameField;
            }
            set {
                this.remitterNameField = value;
                this.RaisePropertyChanged("remitterName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public AddressType remitterAddress {
            get {
                return this.remitterAddressField;
            }
            set {
                this.remitterAddressField = value;
                this.RaisePropertyChanged("remitterAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public contactType remitterContact {
            get {
                return this.remitterContactField;
            }
            set {
                this.remitterContactField = value;
                this.RaisePropertyChanged("remitterContact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("identity", IsNullable=false)]
        public IdentityType[] remitterIdentities {
            get {
                return this.remitterIdentitiesField;
            }
            set {
                this.remitterIdentitiesField = value;
                this.RaisePropertyChanged("remitterIdentities");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public beneficiaryType beneficiaryType {
            get {
                return this.beneficiaryTypeField;
            }
            set {
                this.beneficiaryTypeField = value;
                this.RaisePropertyChanged("beneficiaryType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public nameType beneficiaryName {
            get {
                return this.beneficiaryNameField;
            }
            set {
                this.beneficiaryNameField = value;
                this.RaisePropertyChanged("beneficiaryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public AddressType beneficiaryAddress {
            get {
                return this.beneficiaryAddressField;
            }
            set {
                this.beneficiaryAddressField = value;
                this.RaisePropertyChanged("beneficiaryAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public contactType beneficiaryContact {
            get {
                return this.beneficiaryContactField;
            }
            set {
                this.beneficiaryContactField = value;
                this.RaisePropertyChanged("beneficiaryContact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("identity", IsNullable=false)]
        public IdentityType[] beneficiaryIdentities {
            get {
                return this.beneficiaryIdentitiesField;
            }
            set {
                this.beneficiaryIdentitiesField = value;
                this.RaisePropertyChanged("beneficiaryIdentities");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string beneficiaryAccountNo {
            get {
                return this.beneficiaryAccountNoField;
            }
            set {
                this.beneficiaryAccountNoField = value;
                this.RaisePropertyChanged("beneficiaryAccountNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string beneficiaryIFSC {
            get {
                return this.beneficiaryIFSCField;
            }
            set {
                this.beneficiaryIFSCField = value;
                this.RaisePropertyChanged("beneficiaryIFSC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<transferTypeType> transferType {
            get {
                return this.transferTypeField;
            }
            set {
                this.transferTypeField = value;
                this.RaisePropertyChanged("transferType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<currencyCodeType> transferCurrencyCode {
            get {
                return this.transferCurrencyCodeField;
            }
            set {
                this.transferCurrencyCodeField = value;
                this.RaisePropertyChanged("transferCurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public float transferAmount {
            get {
                return this.transferAmountField;
            }
            set {
                this.transferAmountField = value;
                this.RaisePropertyChanged("transferAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string remitterToBeneficiaryInfo {
            get {
                return this.remitterToBeneficiaryInfoField;
            }
            set {
                this.remitterToBeneficiaryInfoField = value;
                this.RaisePropertyChanged("remitterToBeneficiaryInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string purposeCode {
            get {
                return this.purposeCodeField;
            }
            set {
                this.purposeCodeField = value;
                this.RaisePropertyChanged("purposeCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public enum remitterType {
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        C,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class nameType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fullName", Order=0)]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class reviewStatusType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool reviewRequiredField;
        
        private reviewStatusTypeItemForReview[] itemsForReviewField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool reviewRequired {
            get {
                return this.reviewRequiredField;
            }
            set {
                this.reviewRequiredField = value;
                this.RaisePropertyChanged("reviewRequired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("itemForReview", IsNullable=false)]
        public reviewStatusTypeItemForReview[] itemsForReview {
            get {
                return this.itemsForReviewField;
            }
            set {
                this.itemsForReviewField = value;
                this.RaisePropertyChanged("itemsForReview");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class reviewStatusTypeItemForReview : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string justificationCodeField;
        
        private string justificationTextField;
        
        private reviewStatusTypeItemForReviewStatusCode statusCodeField;
        
        private System.DateTime reviewedOnField;
        
        private string reviewRemarkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
        public string justificationCode {
            get {
                return this.justificationCodeField;
            }
            set {
                this.justificationCodeField = value;
                this.RaisePropertyChanged("justificationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string justificationText {
            get {
                return this.justificationTextField;
            }
            set {
                this.justificationTextField = value;
                this.RaisePropertyChanged("justificationText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public reviewStatusTypeItemForReviewStatusCode statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime reviewedOn {
            get {
                return this.reviewedOnField;
            }
            set {
                this.reviewedOnField = value;
                this.RaisePropertyChanged("reviewedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string reviewRemark {
            get {
                return this.reviewRemarkField;
            }
            set {
                this.reviewRemarkField = value;
                this.RaisePropertyChanged("reviewRemark");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public enum reviewStatusTypeItemForReviewStatusCode {
        
        /// <remarks/>
        COMPLETED,
        
        /// <remarks/>
        PENDING,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class transactionStatusType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private transactionStatusTypeStatusCode statusCodeField;
        
        private string subStatusCodeField;
        
        private string bankReferenceNoField;
        
        private string beneficiaryReferenceNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public transactionStatusTypeStatusCode statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string subStatusCode {
            get {
                return this.subStatusCodeField;
            }
            set {
                this.subStatusCodeField = value;
                this.RaisePropertyChanged("subStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string bankReferenceNo {
            get {
                return this.bankReferenceNoField;
            }
            set {
                this.bankReferenceNoField = value;
                this.RaisePropertyChanged("bankReferenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string beneficiaryReferenceNo {
            get {
                return this.beneficiaryReferenceNoField;
            }
            set {
                this.beneficiaryReferenceNoField = value;
                this.RaisePropertyChanged("beneficiaryReferenceNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public enum transactionStatusTypeStatusCode {
        
        /// <remarks/>
        ONHOLD,
        
        /// <remarks/>
        SENT_TO_BENEFICIARY,
        
        /// <remarks/>
        COMPLETED,
        
        /// <remarks/>
        IN_PROCESS,
        
        /// <remarks/>
        RETURNED_FROM_BENEFICIARY,
        
        /// <remarks/>
        FAILED,
        
        /// <remarks/>
        SCHEDULED_FOR_NEXT_WORKDAY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class IdentityType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expiryDate", typeof(System.DateTime), DataType="date", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("idCountry", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("idNumber", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("idType", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("issueDate", typeof(System.DateTime), DataType="date", Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
                this.RaisePropertyChanged("ItemsElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        expiryDate,
        
        /// <remarks/>
        idCountry,
        
        /// <remarks/>
        idNumber,
        
        /// <remarks/>
        idType,
        
        /// <remarks/>
        issueDate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class contactType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mobileNoField;
        
        private string emailIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string mobileNo {
            get {
                return this.mobileNoField;
            }
            set {
                this.mobileNoField = value;
                this.RaisePropertyChanged("mobileNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string emailID {
            get {
                return this.emailIDField;
            }
            set {
                this.emailIDField = value;
                this.RaisePropertyChanged("emailID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class AddressType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string address1Field;
        
        private string address2Field;
        
        private string address3Field;
        
        private string postalCodeField;
        
        private string cityField;
        
        private string stateOrProvinceField;
        
        private string countryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
                this.RaisePropertyChanged("address1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string address3 {
            get {
                return this.address3Field;
            }
            set {
                this.address3Field = value;
                this.RaisePropertyChanged("address3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("postalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string stateOrProvince {
            get {
                return this.stateOrProvinceField;
            }
            set {
                this.stateOrProvinceField = value;
                this.RaisePropertyChanged("stateOrProvince");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public enum beneficiaryType {
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        C,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public enum transferTypeType {
        
        /// <remarks/>
        NEFT,
        
        /// <remarks/>
        IMPS,
        
        /// <remarks/>
        FT,
        
        /// <remarks/>
        ANY,
        
        /// <remarks/>
        RTGS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public enum currencyCodeType {
        
        /// <remarks/>
        INR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class remitResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string uniqueResponseNoField;
        
        private string attemptNoField;
        
        private System.Nullable<transferTypeType> transferTypeField;
        
        private System.Nullable<bool> lowBalanceAlertField;
        
        private transactionStatusType transactionStatusField;
        
        private reviewStatusType reviewStatusField;
        
        private string requestReferenceNoField;
        
        private decimal transferAmountField;
        
        private bool transferAmountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string uniqueResponseNo {
            get {
                return this.uniqueResponseNoField;
            }
            set {
                this.uniqueResponseNoField = value;
                this.RaisePropertyChanged("uniqueResponseNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=2)]
        public string attemptNo {
            get {
                return this.attemptNoField;
            }
            set {
                this.attemptNoField = value;
                this.RaisePropertyChanged("attemptNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<transferTypeType> transferType {
            get {
                return this.transferTypeField;
            }
            set {
                this.transferTypeField = value;
                this.RaisePropertyChanged("transferType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<bool> lowBalanceAlert {
            get {
                return this.lowBalanceAlertField;
            }
            set {
                this.lowBalanceAlertField = value;
                this.RaisePropertyChanged("lowBalanceAlert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public transactionStatusType transactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
                this.RaisePropertyChanged("transactionStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public reviewStatusType reviewStatus {
            get {
                return this.reviewStatusField;
            }
            set {
                this.reviewStatusField = value;
                this.RaisePropertyChanged("reviewStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string requestReferenceNo {
            get {
                return this.requestReferenceNoField;
            }
            set {
                this.requestReferenceNoField = value;
                this.RaisePropertyChanged("requestReferenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal transferAmount {
            get {
                return this.transferAmountField;
            }
            set {
                this.transferAmountField = value;
                this.RaisePropertyChanged("transferAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transferAmountSpecified {
            get {
                return this.transferAmountFieldSpecified;
            }
            set {
                this.transferAmountFieldSpecified = value;
                this.RaisePropertyChanged("transferAmountSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class remitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBankingASP.NET.com.quantiguous.inw.remit remit;
        
        public remitRequest() {
        }
        
        public remitRequest(APIBankingASP.NET.com.quantiguous.inw.remit remit) {
            this.remit = remit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class remitResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBankingASP.NET.com.quantiguous.inw.remitResponse remitResponse;
        
        public remitResponse1() {
        }
        
        public remitResponse1(APIBankingASP.NET.com.quantiguous.inw.remitResponse remitResponse) {
            this.remitResponse = remitResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class getBalance : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string partnerCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", IsNullable=true, Order=1)]
        public string partnerCode {
            get {
                return this.partnerCodeField;
            }
            set {
                this.partnerCodeField = value;
                this.RaisePropertyChanged("partnerCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class getBalanceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private currencyCodeType accountCurrencyCodeField;
        
        private float accountBalanceAmountField;
        
        private System.Nullable<bool> lowBalanceAlertField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public currencyCodeType accountCurrencyCode {
            get {
                return this.accountCurrencyCodeField;
            }
            set {
                this.accountCurrencyCodeField = value;
                this.RaisePropertyChanged("accountCurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float accountBalanceAmount {
            get {
                return this.accountBalanceAmountField;
            }
            set {
                this.accountBalanceAmountField = value;
                this.RaisePropertyChanged("accountBalanceAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<bool> lowBalanceAlert {
            get {
                return this.lowBalanceAlertField;
            }
            set {
                this.lowBalanceAlertField = value;
                this.RaisePropertyChanged("lowBalanceAlert");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBankingASP.NET.com.quantiguous.inw.getBalance getBalance;
        
        public getBalanceRequest() {
        }
        
        public getBalanceRequest(APIBankingASP.NET.com.quantiguous.inw.getBalance getBalance) {
            this.getBalance = getBalance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBalanceResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBankingASP.NET.com.quantiguous.inw.getBalanceResponse getBalanceResponse;
        
        public getBalanceResponse1() {
        }
        
        public getBalanceResponse1(APIBankingASP.NET.com.quantiguous.inw.getBalanceResponse getBalanceResponse) {
            this.getBalanceResponse = getBalanceResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class getRemittanceStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string partnerCodeField;
        
        private string requestReferenceNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", IsNullable=true, Order=1)]
        public string partnerCode {
            get {
                return this.partnerCodeField;
            }
            set {
                this.partnerCodeField = value;
                this.RaisePropertyChanged("partnerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string requestReferenceNo {
            get {
                return this.requestReferenceNoField;
            }
            set {
                this.requestReferenceNoField = value;
                this.RaisePropertyChanged("requestReferenceNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class getRemittanceStatusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private transferTypeType transferTypeField;
        
        private transferTypeType reqTransferTypeField;
        
        private System.DateTime transactionDateField;
        
        private float transferAmountField;
        
        private currencyCodeType transferCurrencyCodeField;
        
        private transactionStatusType transactionStatusField;
        
        private reviewStatusType reviewStatusField;
        
        private string requestReferenceNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public transferTypeType transferType {
            get {
                return this.transferTypeField;
            }
            set {
                this.transferTypeField = value;
                this.RaisePropertyChanged("transferType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public transferTypeType reqTransferType {
            get {
                return this.reqTransferTypeField;
            }
            set {
                this.reqTransferTypeField = value;
                this.RaisePropertyChanged("reqTransferType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime transactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
                this.RaisePropertyChanged("transactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public float transferAmount {
            get {
                return this.transferAmountField;
            }
            set {
                this.transferAmountField = value;
                this.RaisePropertyChanged("transferAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public currencyCodeType transferCurrencyCode {
            get {
                return this.transferCurrencyCodeField;
            }
            set {
                this.transferCurrencyCodeField = value;
                this.RaisePropertyChanged("transferCurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public transactionStatusType transactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
                this.RaisePropertyChanged("transactionStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public reviewStatusType reviewStatus {
            get {
                return this.reviewStatusField;
            }
            set {
                this.reviewStatusField = value;
                this.RaisePropertyChanged("reviewStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string requestReferenceNo {
            get {
                return this.requestReferenceNoField;
            }
            set {
                this.requestReferenceNoField = value;
                this.RaisePropertyChanged("requestReferenceNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRemittanceStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBankingASP.NET.com.quantiguous.inw.getRemittanceStatus getRemittanceStatus;
        
        public getRemittanceStatusRequest() {
        }
        
        public getRemittanceStatusRequest(APIBankingASP.NET.com.quantiguous.inw.getRemittanceStatus getRemittanceStatus) {
            this.getRemittanceStatus = getRemittanceStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRemittanceStatusResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBankingASP.NET.com.quantiguous.inw.getRemittanceStatusResponse getRemittanceStatusResponse;
        
        public getRemittanceStatusResponse1() {
        }
        
        public getRemittanceStatusResponse1(APIBankingASP.NET.com.quantiguous.inw.getRemittanceStatusResponse getRemittanceStatusResponse) {
            this.getRemittanceStatusResponse = getRemittanceStatusResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InwardRemittanceByPartnerServiceChannel : APIBankingASP.NET.com.quantiguous.inw.InwardRemittanceByPartnerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InwardRemittanceByPartnerServiceClient : System.ServiceModel.ClientBase<APIBankingASP.NET.com.quantiguous.inw.InwardRemittanceByPartnerService>, APIBankingASP.NET.com.quantiguous.inw.InwardRemittanceByPartnerService {
        
        public InwardRemittanceByPartnerServiceClient() {
        }
        
        public InwardRemittanceByPartnerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InwardRemittanceByPartnerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InwardRemittanceByPartnerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InwardRemittanceByPartnerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIBankingASP.NET.com.quantiguous.inw.remitResponse1 APIBankingASP.NET.com.quantiguous.inw.InwardRemittanceByPartnerService.remit(APIBankingASP.NET.com.quantiguous.inw.remitRequest request) {
            return base.Channel.remit(request);
        }
        
        public APIBankingASP.NET.com.quantiguous.inw.remitResponse remit(APIBankingASP.NET.com.quantiguous.inw.remit remit1) {
            APIBankingASP.NET.com.quantiguous.inw.remitRequest inValue = new APIBankingASP.NET.com.quantiguous.inw.remitRequest();
            inValue.remit = remit1;
            APIBankingASP.NET.com.quantiguous.inw.remitResponse1 retVal = ((APIBankingASP.NET.com.quantiguous.inw.InwardRemittanceByPartnerService)(this)).remit(inValue);
            return retVal.remitResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.inw.remitResponse1> APIBankingASP.NET.com.quantiguous.inw.InwardRemittanceByPartnerService.remitAsync(APIBankingASP.NET.com.quantiguous.inw.remitRequest request) {
            return base.Channel.remitAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.inw.remitResponse1> remitAsync(APIBankingASP.NET.com.quantiguous.inw.remit remit) {
            APIBankingASP.NET.com.quantiguous.inw.remitRequest inValue = new APIBankingASP.NET.com.quantiguous.inw.remitRequest();
            inValue.remit = remit;
            return ((APIBankingASP.NET.com.quantiguous.inw.InwardRemittanceByPartnerService)(this)).remitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIBankingASP.NET.com.quantiguous.inw.getBalanceResponse1 APIBankingASP.NET.com.quantiguous.inw.InwardRemittanceByPartnerService.getBalance(APIBankingASP.NET.com.quantiguous.inw.getBalanceRequest request) {
            return base.Channel.getBalance(request);
        }
        
        public APIBankingASP.NET.com.quantiguous.inw.getBalanceResponse getBalance(APIBankingASP.NET.com.quantiguous.inw.getBalance getBalance1) {
            APIBankingASP.NET.com.quantiguous.inw.getBalanceRequest inValue = new APIBankingASP.NET.com.quantiguous.inw.getBalanceRequest();
            inValue.getBalance = getBalance1;
            APIBankingASP.NET.com.quantiguous.inw.getBalanceResponse1 retVal = ((APIBankingASP.NET.com.quantiguous.inw.InwardRemittanceByPartnerService)(this)).getBalance(inValue);
            return retVal.getBalanceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.inw.getBalanceResponse1> APIBankingASP.NET.com.quantiguous.inw.InwardRemittanceByPartnerService.getBalanceAsync(APIBankingASP.NET.com.quantiguous.inw.getBalanceRequest request) {
            return base.Channel.getBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.inw.getBalanceResponse1> getBalanceAsync(APIBankingASP.NET.com.quantiguous.inw.getBalance getBalance) {
            APIBankingASP.NET.com.quantiguous.inw.getBalanceRequest inValue = new APIBankingASP.NET.com.quantiguous.inw.getBalanceRequest();
            inValue.getBalance = getBalance;
            return ((APIBankingASP.NET.com.quantiguous.inw.InwardRemittanceByPartnerService)(this)).getBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIBankingASP.NET.com.quantiguous.inw.getRemittanceStatusResponse1 APIBankingASP.NET.com.quantiguous.inw.InwardRemittanceByPartnerService.getRemittanceStatus(APIBankingASP.NET.com.quantiguous.inw.getRemittanceStatusRequest request) {
            return base.Channel.getRemittanceStatus(request);
        }
        
        public APIBankingASP.NET.com.quantiguous.inw.getRemittanceStatusResponse getRemittanceStatus(APIBankingASP.NET.com.quantiguous.inw.getRemittanceStatus getRemittanceStatus1) {
            APIBankingASP.NET.com.quantiguous.inw.getRemittanceStatusRequest inValue = new APIBankingASP.NET.com.quantiguous.inw.getRemittanceStatusRequest();
            inValue.getRemittanceStatus = getRemittanceStatus1;
            APIBankingASP.NET.com.quantiguous.inw.getRemittanceStatusResponse1 retVal = ((APIBankingASP.NET.com.quantiguous.inw.InwardRemittanceByPartnerService)(this)).getRemittanceStatus(inValue);
            return retVal.getRemittanceStatusResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.inw.getRemittanceStatusResponse1> APIBankingASP.NET.com.quantiguous.inw.InwardRemittanceByPartnerService.getRemittanceStatusAsync(APIBankingASP.NET.com.quantiguous.inw.getRemittanceStatusRequest request) {
            return base.Channel.getRemittanceStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.inw.getRemittanceStatusResponse1> getRemittanceStatusAsync(APIBankingASP.NET.com.quantiguous.inw.getRemittanceStatus getRemittanceStatus) {
            APIBankingASP.NET.com.quantiguous.inw.getRemittanceStatusRequest inValue = new APIBankingASP.NET.com.quantiguous.inw.getRemittanceStatusRequest();
            inValue.getRemittanceStatus = getRemittanceStatus;
            return ((APIBankingASP.NET.com.quantiguous.inw.InwardRemittanceByPartnerService)(this)).getRemittanceStatusAsync(inValue);
        }
    }
}
