//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIBankingASP.NET.com.quantiguous.imt {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.quantiguous.com/services", ConfigurationName="com.quantiguous.imt.IMTService")]
    public interface IMTService {
        
        // CODEGEN: Generating message contract since the operation addBeneficiary is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/IMTService/addBeneficiary", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIBankingASP.NET.com.quantiguous.imt.addBeneficiaryResponse1 addBeneficiary(APIBankingASP.NET.com.quantiguous.imt.addBeneficiaryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/IMTService/addBeneficiary", ReplyAction="*")]
        System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.imt.addBeneficiaryResponse1> addBeneficiaryAsync(APIBankingASP.NET.com.quantiguous.imt.addBeneficiaryRequest request);
        
        // CODEGEN: Generating message contract since the operation deleteBeneficiary is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/IMTService/deleteBeneficiary", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIBankingASP.NET.com.quantiguous.imt.deleteBeneficiaryResponse1 deleteBeneficiary(APIBankingASP.NET.com.quantiguous.imt.deleteBeneficiaryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/IMTService/deleteBeneficiary", ReplyAction="*")]
        System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.imt.deleteBeneficiaryResponse1> deleteBeneficiaryAsync(APIBankingASP.NET.com.quantiguous.imt.deleteBeneficiaryRequest request);
        
        // CODEGEN: Generating message contract since the operation initiateTransfer is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/IMTService/initiateTransfer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIBankingASP.NET.com.quantiguous.imt.initiateTransferResponse1 initiateTransfer(APIBankingASP.NET.com.quantiguous.imt.initiateTransferRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/IMTService/initiateTransfer", ReplyAction="*")]
        System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.imt.initiateTransferResponse1> initiateTransferAsync(APIBankingASP.NET.com.quantiguous.imt.initiateTransferRequest request);
        
        // CODEGEN: Generating message contract since the operation getTransferStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/IMTService/getTransferStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIBankingASP.NET.com.quantiguous.imt.getTransferStatusResponse1 getTransferStatus(APIBankingASP.NET.com.quantiguous.imt.getTransferStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/IMTService/getTransferStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.imt.getTransferStatusResponse1> getTransferStatusAsync(APIBankingASP.NET.com.quantiguous.imt.getTransferStatusRequest request);
        
        // CODEGEN: Generating message contract since the operation cancelTransfer is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/IMTService/cancelTransfer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIBankingASP.NET.com.quantiguous.imt.cancelTransferResponse1 cancelTransfer(APIBankingASP.NET.com.quantiguous.imt.cancelTransferRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/IMTService/cancelTransfer", ReplyAction="*")]
        System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.imt.cancelTransferResponse1> cancelTransferAsync(APIBankingASP.NET.com.quantiguous.imt.cancelTransferRequest request);
        
        // CODEGEN: Generating message contract since the operation getBeneficiaries is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/IMTService/getBeneficiaries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIBankingASP.NET.com.quantiguous.imt.getBeneficiariesResponse1 getBeneficiaries(APIBankingASP.NET.com.quantiguous.imt.getBeneficiariesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/IMTService/getBeneficiaries", ReplyAction="*")]
        System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.imt.getBeneficiariesResponse1> getBeneficiariesAsync(APIBankingASP.NET.com.quantiguous.imt.getBeneficiariesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class addBeneficiary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string uniqueRequestNoField;
        
        private string appIDField;
        
        private string customerIDField;
        
        private string beneficiaryMobileNoField;
        
        private string beneficiaryNameField;
        
        private beneficiaryAddressType beneficiaryAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string uniqueRequestNo {
            get {
                return this.uniqueRequestNoField;
            }
            set {
                this.uniqueRequestNoField = value;
                this.RaisePropertyChanged("uniqueRequestNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string appID {
            get {
                return this.appIDField;
            }
            set {
                this.appIDField = value;
                this.RaisePropertyChanged("appID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("customerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string beneficiaryMobileNo {
            get {
                return this.beneficiaryMobileNoField;
            }
            set {
                this.beneficiaryMobileNoField = value;
                this.RaisePropertyChanged("beneficiaryMobileNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string beneficiaryName {
            get {
                return this.beneficiaryNameField;
            }
            set {
                this.beneficiaryNameField = value;
                this.RaisePropertyChanged("beneficiaryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public beneficiaryAddressType beneficiaryAddress {
            get {
                return this.beneficiaryAddressField;
            }
            set {
                this.beneficiaryAddressField = value;
                this.RaisePropertyChanged("beneficiaryAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class beneficiaryAddressType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressLineField;
        
        private string cityNameField;
        
        private string postalCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string addressLine {
            get {
                return this.addressLineField;
            }
            set {
                this.addressLineField = value;
                this.RaisePropertyChanged("addressLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
                this.RaisePropertyChanged("cityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("postalCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class beneficiaryType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string beneficiaryNameField;
        
        private string beneficiaryMobileNoField;
        
        private System.DateTime registrationDateField;
        
        private string addressLineField;
        
        private string postalCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string beneficiaryName {
            get {
                return this.beneficiaryNameField;
            }
            set {
                this.beneficiaryNameField = value;
                this.RaisePropertyChanged("beneficiaryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string beneficiaryMobileNo {
            get {
                return this.beneficiaryMobileNoField;
            }
            set {
                this.beneficiaryMobileNoField = value;
                this.RaisePropertyChanged("beneficiaryMobileNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime registrationDate {
            get {
                return this.registrationDateField;
            }
            set {
                this.registrationDateField = value;
                this.RaisePropertyChanged("registrationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string addressLine {
            get {
                return this.addressLineField;
            }
            set {
                this.addressLineField = value;
                this.RaisePropertyChanged("addressLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("postalCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class cancelResultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string imtReferenceNoField;
        
        private string bankReferenceNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string imtReferenceNo {
            get {
                return this.imtReferenceNoField;
            }
            set {
                this.imtReferenceNoField = value;
                this.RaisePropertyChanged("imtReferenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string bankReferenceNo {
            get {
                return this.bankReferenceNoField;
            }
            set {
                this.bankReferenceNoField = value;
                this.RaisePropertyChanged("bankReferenceNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class IMTTransferStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string imtReferenceNoField;
        
        private IMTTransferStatusStatusCode statusCodeField;
        
        private string customerIDField;
        
        private string beneficiaryMobileNoField;
        
        private float transferAmountField;
        
        private string remitterToBeneficiaryInfoField;
        
        private System.DateTime expiryDateField;
        
        private System.DateTime initiatedAtField;
        
        private System.DateTime itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string imtReferenceNo {
            get {
                return this.imtReferenceNoField;
            }
            set {
                this.imtReferenceNoField = value;
                this.RaisePropertyChanged("imtReferenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IMTTransferStatusStatusCode statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("customerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string beneficiaryMobileNo {
            get {
                return this.beneficiaryMobileNoField;
            }
            set {
                this.beneficiaryMobileNoField = value;
                this.RaisePropertyChanged("beneficiaryMobileNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public float transferAmount {
            get {
                return this.transferAmountField;
            }
            set {
                this.transferAmountField = value;
                this.RaisePropertyChanged("transferAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string remitterToBeneficiaryInfo {
            get {
                return this.remitterToBeneficiaryInfoField;
            }
            set {
                this.remitterToBeneficiaryInfoField = value;
                this.RaisePropertyChanged("remitterToBeneficiaryInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
                this.RaisePropertyChanged("expiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=7)]
        public System.DateTime initiatedAt {
            get {
                return this.initiatedAtField;
            }
            set {
                this.initiatedAtField = value;
                this.RaisePropertyChanged("initiatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cancelledAt", typeof(System.DateTime), DataType="date", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute("completedAt", typeof(System.DateTime), DataType="date", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute("expiredDate", typeof(System.DateTime), DataType="date", Order=8)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public System.DateTime Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public enum IMTTransferStatusStatusCode {
        
        /// <remarks/>
        INITIATED,
        
        /// <remarks/>
        COMPLETED,
        
        /// <remarks/>
        EXPIRED,
        
        /// <remarks/>
        CANCELLED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        cancelledAt,
        
        /// <remarks/>
        completedAt,
        
        /// <remarks/>
        expiredDate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class initiateTransferResultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bankReferenceNoField;
        
        private string imtReferenceNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string bankReferenceNo {
            get {
                return this.bankReferenceNoField;
            }
            set {
                this.bankReferenceNoField = value;
                this.RaisePropertyChanged("bankReferenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string imtReferenceNo {
            get {
                return this.imtReferenceNoField;
            }
            set {
                this.imtReferenceNoField = value;
                this.RaisePropertyChanged("imtReferenceNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class addBeneficiaryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string uniqueResponseNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string uniqueResponseNo {
            get {
                return this.uniqueResponseNoField;
            }
            set {
                this.uniqueResponseNoField = value;
                this.RaisePropertyChanged("uniqueResponseNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addBeneficiaryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBankingASP.NET.com.quantiguous.imt.addBeneficiary addBeneficiary;
        
        public addBeneficiaryRequest() {
        }
        
        public addBeneficiaryRequest(APIBankingASP.NET.com.quantiguous.imt.addBeneficiary addBeneficiary) {
            this.addBeneficiary = addBeneficiary;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addBeneficiaryResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBankingASP.NET.com.quantiguous.imt.addBeneficiaryResponse addBeneficiaryResponse;
        
        public addBeneficiaryResponse1() {
        }
        
        public addBeneficiaryResponse1(APIBankingASP.NET.com.quantiguous.imt.addBeneficiaryResponse addBeneficiaryResponse) {
            this.addBeneficiaryResponse = addBeneficiaryResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class deleteBeneficiary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string uniqueRequestNoField;
        
        private string appIDField;
        
        private string customerIDField;
        
        private string beneficiaryMobileNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string uniqueRequestNo {
            get {
                return this.uniqueRequestNoField;
            }
            set {
                this.uniqueRequestNoField = value;
                this.RaisePropertyChanged("uniqueRequestNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string appID {
            get {
                return this.appIDField;
            }
            set {
                this.appIDField = value;
                this.RaisePropertyChanged("appID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("customerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string beneficiaryMobileNo {
            get {
                return this.beneficiaryMobileNoField;
            }
            set {
                this.beneficiaryMobileNoField = value;
                this.RaisePropertyChanged("beneficiaryMobileNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class deleteBeneficiaryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string uniqueResponseNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string uniqueResponseNo {
            get {
                return this.uniqueResponseNoField;
            }
            set {
                this.uniqueResponseNoField = value;
                this.RaisePropertyChanged("uniqueResponseNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteBeneficiaryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBankingASP.NET.com.quantiguous.imt.deleteBeneficiary deleteBeneficiary;
        
        public deleteBeneficiaryRequest() {
        }
        
        public deleteBeneficiaryRequest(APIBankingASP.NET.com.quantiguous.imt.deleteBeneficiary deleteBeneficiary) {
            this.deleteBeneficiary = deleteBeneficiary;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteBeneficiaryResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBankingASP.NET.com.quantiguous.imt.deleteBeneficiaryResponse deleteBeneficiaryResponse;
        
        public deleteBeneficiaryResponse1() {
        }
        
        public deleteBeneficiaryResponse1(APIBankingASP.NET.com.quantiguous.imt.deleteBeneficiaryResponse deleteBeneficiaryResponse) {
            this.deleteBeneficiaryResponse = deleteBeneficiaryResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class initiateTransfer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string uniqueRequestNoField;
        
        private string appIDField;
        
        private string customerIDField;
        
        private string beneficiaryMobileNoField;
        
        private float transferAmountField;
        
        private string passCodeField;
        
        private string remitterToBeneficiaryInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string uniqueRequestNo {
            get {
                return this.uniqueRequestNoField;
            }
            set {
                this.uniqueRequestNoField = value;
                this.RaisePropertyChanged("uniqueRequestNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string appID {
            get {
                return this.appIDField;
            }
            set {
                this.appIDField = value;
                this.RaisePropertyChanged("appID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("customerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string beneficiaryMobileNo {
            get {
                return this.beneficiaryMobileNoField;
            }
            set {
                this.beneficiaryMobileNoField = value;
                this.RaisePropertyChanged("beneficiaryMobileNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public float transferAmount {
            get {
                return this.transferAmountField;
            }
            set {
                this.transferAmountField = value;
                this.RaisePropertyChanged("transferAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string passCode {
            get {
                return this.passCodeField;
            }
            set {
                this.passCodeField = value;
                this.RaisePropertyChanged("passCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string remitterToBeneficiaryInfo {
            get {
                return this.remitterToBeneficiaryInfoField;
            }
            set {
                this.remitterToBeneficiaryInfoField = value;
                this.RaisePropertyChanged("remitterToBeneficiaryInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class initiateTransferResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string uniqueResponseNoField;
        
        private initiateTransferResultType initiateTransferResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string uniqueResponseNo {
            get {
                return this.uniqueResponseNoField;
            }
            set {
                this.uniqueResponseNoField = value;
                this.RaisePropertyChanged("uniqueResponseNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public initiateTransferResultType initiateTransferResult {
            get {
                return this.initiateTransferResultField;
            }
            set {
                this.initiateTransferResultField = value;
                this.RaisePropertyChanged("initiateTransferResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class initiateTransferRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBankingASP.NET.com.quantiguous.imt.initiateTransfer initiateTransfer;
        
        public initiateTransferRequest() {
        }
        
        public initiateTransferRequest(APIBankingASP.NET.com.quantiguous.imt.initiateTransfer initiateTransfer) {
            this.initiateTransfer = initiateTransfer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class initiateTransferResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBankingASP.NET.com.quantiguous.imt.initiateTransferResponse initiateTransferResponse;
        
        public initiateTransferResponse1() {
        }
        
        public initiateTransferResponse1(APIBankingASP.NET.com.quantiguous.imt.initiateTransferResponse initiateTransferResponse) {
            this.initiateTransferResponse = initiateTransferResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class getTransferStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string appIDField;
        
        private string customerIDField;
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string appID {
            get {
                return this.appIDField;
            }
            set {
                this.appIDField = value;
                this.RaisePropertyChanged("appID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("customerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("imtReferenceNo", typeof(string), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("initiateTransferRequestNo", typeof(string), Order=3)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        imtReferenceNo,
        
        /// <remarks/>
        initiateTransferRequestNo,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class getTransferStatusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private IMTTransferStatus transferStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IMTTransferStatus transferStatus {
            get {
                return this.transferStatusField;
            }
            set {
                this.transferStatusField = value;
                this.RaisePropertyChanged("transferStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTransferStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBankingASP.NET.com.quantiguous.imt.getTransferStatus getTransferStatus;
        
        public getTransferStatusRequest() {
        }
        
        public getTransferStatusRequest(APIBankingASP.NET.com.quantiguous.imt.getTransferStatus getTransferStatus) {
            this.getTransferStatus = getTransferStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTransferStatusResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBankingASP.NET.com.quantiguous.imt.getTransferStatusResponse getTransferStatusResponse;
        
        public getTransferStatusResponse1() {
        }
        
        public getTransferStatusResponse1(APIBankingASP.NET.com.quantiguous.imt.getTransferStatusResponse getTransferStatusResponse) {
            this.getTransferStatusResponse = getTransferStatusResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class cancelTransfer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string uniqueRequestNoField;
        
        private string appIDField;
        
        private string customerIDField;
        
        private string initiateTransferRequestNoField;
        
        private string reasonToCancelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string uniqueRequestNo {
            get {
                return this.uniqueRequestNoField;
            }
            set {
                this.uniqueRequestNoField = value;
                this.RaisePropertyChanged("uniqueRequestNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string appID {
            get {
                return this.appIDField;
            }
            set {
                this.appIDField = value;
                this.RaisePropertyChanged("appID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("customerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string initiateTransferRequestNo {
            get {
                return this.initiateTransferRequestNoField;
            }
            set {
                this.initiateTransferRequestNoField = value;
                this.RaisePropertyChanged("initiateTransferRequestNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string reasonToCancel {
            get {
                return this.reasonToCancelField;
            }
            set {
                this.reasonToCancelField = value;
                this.RaisePropertyChanged("reasonToCancel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class cancelTransferResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string uniqueResponseNoField;
        
        private cancelResultType cancelResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string uniqueResponseNo {
            get {
                return this.uniqueResponseNoField;
            }
            set {
                this.uniqueResponseNoField = value;
                this.RaisePropertyChanged("uniqueResponseNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public cancelResultType cancelResult {
            get {
                return this.cancelResultField;
            }
            set {
                this.cancelResultField = value;
                this.RaisePropertyChanged("cancelResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelTransferRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBankingASP.NET.com.quantiguous.imt.cancelTransfer cancelTransfer;
        
        public cancelTransferRequest() {
        }
        
        public cancelTransferRequest(APIBankingASP.NET.com.quantiguous.imt.cancelTransfer cancelTransfer) {
            this.cancelTransfer = cancelTransfer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelTransferResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBankingASP.NET.com.quantiguous.imt.cancelTransferResponse cancelTransferResponse;
        
        public cancelTransferResponse1() {
        }
        
        public cancelTransferResponse1(APIBankingASP.NET.com.quantiguous.imt.cancelTransferResponse cancelTransferResponse) {
            this.cancelTransferResponse = cancelTransferResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class getBeneficiaries : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string appIDField;
        
        private string customerIDField;
        
        private getBeneficiariesDateRange dateRangeField;
        
        private string numBeneficiariesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string appID {
            get {
                return this.appIDField;
            }
            set {
                this.appIDField = value;
                this.RaisePropertyChanged("appID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("customerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public getBeneficiariesDateRange dateRange {
            get {
                return this.dateRangeField;
            }
            set {
                this.dateRangeField = value;
                this.RaisePropertyChanged("dateRange");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=4)]
        public string numBeneficiaries {
            get {
                return this.numBeneficiariesField;
            }
            set {
                this.numBeneficiariesField = value;
                this.RaisePropertyChanged("numBeneficiaries");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class getBeneficiariesDateRange : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fromDateField;
        
        private System.DateTime toDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime fromDate {
            get {
                return this.fromDateField;
            }
            set {
                this.fromDateField = value;
                this.RaisePropertyChanged("fromDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime toDate {
            get {
                return this.toDateField;
            }
            set {
                this.toDateField = value;
                this.RaisePropertyChanged("toDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class getBeneficiariesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string numBeneficiariesField;
        
        private beneficiaryType[] beneficiariesArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=1)]
        public string numBeneficiaries {
            get {
                return this.numBeneficiariesField;
            }
            set {
                this.numBeneficiariesField = value;
                this.RaisePropertyChanged("numBeneficiaries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("beneficiary", IsNullable=false)]
        public beneficiaryType[] beneficiariesArray {
            get {
                return this.beneficiariesArrayField;
            }
            set {
                this.beneficiariesArrayField = value;
                this.RaisePropertyChanged("beneficiariesArray");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBeneficiariesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBankingASP.NET.com.quantiguous.imt.getBeneficiaries getBeneficiaries;
        
        public getBeneficiariesRequest() {
        }
        
        public getBeneficiariesRequest(APIBankingASP.NET.com.quantiguous.imt.getBeneficiaries getBeneficiaries) {
            this.getBeneficiaries = getBeneficiaries;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBeneficiariesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBankingASP.NET.com.quantiguous.imt.getBeneficiariesResponse getBeneficiariesResponse;
        
        public getBeneficiariesResponse1() {
        }
        
        public getBeneficiariesResponse1(APIBankingASP.NET.com.quantiguous.imt.getBeneficiariesResponse getBeneficiariesResponse) {
            this.getBeneficiariesResponse = getBeneficiariesResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMTServiceChannel : APIBankingASP.NET.com.quantiguous.imt.IMTService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MTServiceClient : System.ServiceModel.ClientBase<APIBankingASP.NET.com.quantiguous.imt.IMTService>, APIBankingASP.NET.com.quantiguous.imt.IMTService {
        
        public MTServiceClient() {
        }
        
        public MTServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MTServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MTServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MTServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIBankingASP.NET.com.quantiguous.imt.addBeneficiaryResponse1 APIBankingASP.NET.com.quantiguous.imt.IMTService.addBeneficiary(APIBankingASP.NET.com.quantiguous.imt.addBeneficiaryRequest request) {
            return base.Channel.addBeneficiary(request);
        }
        
        public APIBankingASP.NET.com.quantiguous.imt.addBeneficiaryResponse addBeneficiary(APIBankingASP.NET.com.quantiguous.imt.addBeneficiary addBeneficiary1) {
            APIBankingASP.NET.com.quantiguous.imt.addBeneficiaryRequest inValue = new APIBankingASP.NET.com.quantiguous.imt.addBeneficiaryRequest();
            inValue.addBeneficiary = addBeneficiary1;
            APIBankingASP.NET.com.quantiguous.imt.addBeneficiaryResponse1 retVal = ((APIBankingASP.NET.com.quantiguous.imt.IMTService)(this)).addBeneficiary(inValue);
            return retVal.addBeneficiaryResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.imt.addBeneficiaryResponse1> APIBankingASP.NET.com.quantiguous.imt.IMTService.addBeneficiaryAsync(APIBankingASP.NET.com.quantiguous.imt.addBeneficiaryRequest request) {
            return base.Channel.addBeneficiaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.imt.addBeneficiaryResponse1> addBeneficiaryAsync(APIBankingASP.NET.com.quantiguous.imt.addBeneficiary addBeneficiary) {
            APIBankingASP.NET.com.quantiguous.imt.addBeneficiaryRequest inValue = new APIBankingASP.NET.com.quantiguous.imt.addBeneficiaryRequest();
            inValue.addBeneficiary = addBeneficiary;
            return ((APIBankingASP.NET.com.quantiguous.imt.IMTService)(this)).addBeneficiaryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIBankingASP.NET.com.quantiguous.imt.deleteBeneficiaryResponse1 APIBankingASP.NET.com.quantiguous.imt.IMTService.deleteBeneficiary(APIBankingASP.NET.com.quantiguous.imt.deleteBeneficiaryRequest request) {
            return base.Channel.deleteBeneficiary(request);
        }
        
        public APIBankingASP.NET.com.quantiguous.imt.deleteBeneficiaryResponse deleteBeneficiary(APIBankingASP.NET.com.quantiguous.imt.deleteBeneficiary deleteBeneficiary1) {
            APIBankingASP.NET.com.quantiguous.imt.deleteBeneficiaryRequest inValue = new APIBankingASP.NET.com.quantiguous.imt.deleteBeneficiaryRequest();
            inValue.deleteBeneficiary = deleteBeneficiary1;
            APIBankingASP.NET.com.quantiguous.imt.deleteBeneficiaryResponse1 retVal = ((APIBankingASP.NET.com.quantiguous.imt.IMTService)(this)).deleteBeneficiary(inValue);
            return retVal.deleteBeneficiaryResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.imt.deleteBeneficiaryResponse1> APIBankingASP.NET.com.quantiguous.imt.IMTService.deleteBeneficiaryAsync(APIBankingASP.NET.com.quantiguous.imt.deleteBeneficiaryRequest request) {
            return base.Channel.deleteBeneficiaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.imt.deleteBeneficiaryResponse1> deleteBeneficiaryAsync(APIBankingASP.NET.com.quantiguous.imt.deleteBeneficiary deleteBeneficiary) {
            APIBankingASP.NET.com.quantiguous.imt.deleteBeneficiaryRequest inValue = new APIBankingASP.NET.com.quantiguous.imt.deleteBeneficiaryRequest();
            inValue.deleteBeneficiary = deleteBeneficiary;
            return ((APIBankingASP.NET.com.quantiguous.imt.IMTService)(this)).deleteBeneficiaryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIBankingASP.NET.com.quantiguous.imt.initiateTransferResponse1 APIBankingASP.NET.com.quantiguous.imt.IMTService.initiateTransfer(APIBankingASP.NET.com.quantiguous.imt.initiateTransferRequest request) {
            return base.Channel.initiateTransfer(request);
        }
        
        public APIBankingASP.NET.com.quantiguous.imt.initiateTransferResponse initiateTransfer(APIBankingASP.NET.com.quantiguous.imt.initiateTransfer initiateTransfer1) {
            APIBankingASP.NET.com.quantiguous.imt.initiateTransferRequest inValue = new APIBankingASP.NET.com.quantiguous.imt.initiateTransferRequest();
            inValue.initiateTransfer = initiateTransfer1;
            APIBankingASP.NET.com.quantiguous.imt.initiateTransferResponse1 retVal = ((APIBankingASP.NET.com.quantiguous.imt.IMTService)(this)).initiateTransfer(inValue);
            return retVal.initiateTransferResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.imt.initiateTransferResponse1> APIBankingASP.NET.com.quantiguous.imt.IMTService.initiateTransferAsync(APIBankingASP.NET.com.quantiguous.imt.initiateTransferRequest request) {
            return base.Channel.initiateTransferAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.imt.initiateTransferResponse1> initiateTransferAsync(APIBankingASP.NET.com.quantiguous.imt.initiateTransfer initiateTransfer) {
            APIBankingASP.NET.com.quantiguous.imt.initiateTransferRequest inValue = new APIBankingASP.NET.com.quantiguous.imt.initiateTransferRequest();
            inValue.initiateTransfer = initiateTransfer;
            return ((APIBankingASP.NET.com.quantiguous.imt.IMTService)(this)).initiateTransferAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIBankingASP.NET.com.quantiguous.imt.getTransferStatusResponse1 APIBankingASP.NET.com.quantiguous.imt.IMTService.getTransferStatus(APIBankingASP.NET.com.quantiguous.imt.getTransferStatusRequest request) {
            return base.Channel.getTransferStatus(request);
        }
        
        public APIBankingASP.NET.com.quantiguous.imt.getTransferStatusResponse getTransferStatus(APIBankingASP.NET.com.quantiguous.imt.getTransferStatus getTransferStatus1) {
            APIBankingASP.NET.com.quantiguous.imt.getTransferStatusRequest inValue = new APIBankingASP.NET.com.quantiguous.imt.getTransferStatusRequest();
            inValue.getTransferStatus = getTransferStatus1;
            APIBankingASP.NET.com.quantiguous.imt.getTransferStatusResponse1 retVal = ((APIBankingASP.NET.com.quantiguous.imt.IMTService)(this)).getTransferStatus(inValue);
            return retVal.getTransferStatusResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.imt.getTransferStatusResponse1> APIBankingASP.NET.com.quantiguous.imt.IMTService.getTransferStatusAsync(APIBankingASP.NET.com.quantiguous.imt.getTransferStatusRequest request) {
            return base.Channel.getTransferStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.imt.getTransferStatusResponse1> getTransferStatusAsync(APIBankingASP.NET.com.quantiguous.imt.getTransferStatus getTransferStatus) {
            APIBankingASP.NET.com.quantiguous.imt.getTransferStatusRequest inValue = new APIBankingASP.NET.com.quantiguous.imt.getTransferStatusRequest();
            inValue.getTransferStatus = getTransferStatus;
            return ((APIBankingASP.NET.com.quantiguous.imt.IMTService)(this)).getTransferStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIBankingASP.NET.com.quantiguous.imt.cancelTransferResponse1 APIBankingASP.NET.com.quantiguous.imt.IMTService.cancelTransfer(APIBankingASP.NET.com.quantiguous.imt.cancelTransferRequest request) {
            return base.Channel.cancelTransfer(request);
        }
        
        public APIBankingASP.NET.com.quantiguous.imt.cancelTransferResponse cancelTransfer(APIBankingASP.NET.com.quantiguous.imt.cancelTransfer cancelTransfer1) {
            APIBankingASP.NET.com.quantiguous.imt.cancelTransferRequest inValue = new APIBankingASP.NET.com.quantiguous.imt.cancelTransferRequest();
            inValue.cancelTransfer = cancelTransfer1;
            APIBankingASP.NET.com.quantiguous.imt.cancelTransferResponse1 retVal = ((APIBankingASP.NET.com.quantiguous.imt.IMTService)(this)).cancelTransfer(inValue);
            return retVal.cancelTransferResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.imt.cancelTransferResponse1> APIBankingASP.NET.com.quantiguous.imt.IMTService.cancelTransferAsync(APIBankingASP.NET.com.quantiguous.imt.cancelTransferRequest request) {
            return base.Channel.cancelTransferAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.imt.cancelTransferResponse1> cancelTransferAsync(APIBankingASP.NET.com.quantiguous.imt.cancelTransfer cancelTransfer) {
            APIBankingASP.NET.com.quantiguous.imt.cancelTransferRequest inValue = new APIBankingASP.NET.com.quantiguous.imt.cancelTransferRequest();
            inValue.cancelTransfer = cancelTransfer;
            return ((APIBankingASP.NET.com.quantiguous.imt.IMTService)(this)).cancelTransferAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIBankingASP.NET.com.quantiguous.imt.getBeneficiariesResponse1 APIBankingASP.NET.com.quantiguous.imt.IMTService.getBeneficiaries(APIBankingASP.NET.com.quantiguous.imt.getBeneficiariesRequest request) {
            return base.Channel.getBeneficiaries(request);
        }
        
        public APIBankingASP.NET.com.quantiguous.imt.getBeneficiariesResponse getBeneficiaries(APIBankingASP.NET.com.quantiguous.imt.getBeneficiaries getBeneficiaries1) {
            APIBankingASP.NET.com.quantiguous.imt.getBeneficiariesRequest inValue = new APIBankingASP.NET.com.quantiguous.imt.getBeneficiariesRequest();
            inValue.getBeneficiaries = getBeneficiaries1;
            APIBankingASP.NET.com.quantiguous.imt.getBeneficiariesResponse1 retVal = ((APIBankingASP.NET.com.quantiguous.imt.IMTService)(this)).getBeneficiaries(inValue);
            return retVal.getBeneficiariesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.imt.getBeneficiariesResponse1> APIBankingASP.NET.com.quantiguous.imt.IMTService.getBeneficiariesAsync(APIBankingASP.NET.com.quantiguous.imt.getBeneficiariesRequest request) {
            return base.Channel.getBeneficiariesAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIBankingASP.NET.com.quantiguous.imt.getBeneficiariesResponse1> getBeneficiariesAsync(APIBankingASP.NET.com.quantiguous.imt.getBeneficiaries getBeneficiaries) {
            APIBankingASP.NET.com.quantiguous.imt.getBeneficiariesRequest inValue = new APIBankingASP.NET.com.quantiguous.imt.getBeneficiariesRequest();
            inValue.getBeneficiaries = getBeneficiaries;
            return ((APIBankingASP.NET.com.quantiguous.imt.IMTService)(this)).getBeneficiariesAsync(inValue);
        }
    }
}
